### ISSUE TITLE
Make HSQLDB shutdownable

### ISSUE THREAD

**Issue by michhelm** [HHN/crawler4j#279]
Hello,
can we have a configurable shutdown parameter for HSQLDB? When crawler4j runs in a persistent Java environment, the database won't shutdown automatically. Links that were crawled before won't be crawled a second time. The _CrawlController_ marks it as already seen:
https://github.com/rzo1/crawler4j/blob/33ddeb4fb030ba11ad311b9c2b027c9f56659f3e/crawler4j-core/src/main/java/edu/uci/ics/crawler4j/crawler/CrawlController.java#L499

Documentation of the shutdown parameter for HSQLDB: https://www.hsqldb.org/doc/guide/guide.html#rgc_closing_db
Since 1.7.2 the database won't shut down automatically, when there no connections anymore.

This has to go probably here

https://github.com/rzo1/crawler4j/blob/33ddeb4fb030ba11ad311b9c2b027c9f56659f3e/crawler4j-frontier/crawler4j-frontier-hsqldb/src/main/java/de/hshn/mi/crawler4j/frontier/HSQLDBFrontierConfiguration.java#L103-L107

Thank you!

**Comment by rzo1** [comment]
Feel free to provide a PR adding it.
 🙃
